### ISSUE TITLE
Modificación contraseña campos vacios borra contraseña de la BD

### ISSUE THREAD

**Issue by andreagiaco** [fedeolivera1/ProyFinal2017Dsk#11]
Si trato de modificar la CONTRASEÑA y dejo los campos vacios, me muestra error de campos obligatorios pero borra la CONTRASEÑA de la BD

**Comment by fedeolivera1** [comment]
No pude reproducir este error, pero me suena a que tiene que ver con el anterior, el cual dejaba en blanco las constaseñas (en base) al hacer modificación de usuarios, ya que el input de texto está deshabilitado en esa instancia pero guardaba igual este dato ("") en la base.
A REVISAR.
