### ISSUE TITLE
Largo caracteres numeración C.I/Pasaporte

### ISSUE THREAD

**Issue by andreagiaco** [fedeolivera1/ProyFinal2017Dsk#12]
Largo de caracteres en C.I/Pasaporte no discrimina, deja escribir solo caracteres numéricos pero espacio para 25 caracteres.

**Comment by fedeolivera1** [comment]
Este campo pasa a admitir el largo del tipo que lleva en base de datos, por ej, si el dato en base es long como es el caso de doc/rut, pasa a controlar ese largo como válido. En caso inválido, lanzará un msj de advertencia.
