### ISSUE TITLE
Ingreso de C.I/Pasaporte con puntos Error

### ISSUE THREAD

**Issue by andreagiaco** [fedeolivera1/ProyFinal2017Dsk#13]
Permite ingreso de puntos entre caracteres numéricos, no ingresa y muestra Error excepción for Input String

**Comment by fedeolivera1** [comment]
Se impactaron metodos tanto para el input como para las salidas de los campos, para que admita numeros de varios tipos (int, long y double). Tambien se impactan metodos para el correcto ingreso de numeros decimales (por ej km en PF).

Metodos impactados:
-isNumericInt (salida del campo)
-isNumericLong (salida del campo)
-isNumericDbl (salida del campo)
-keyTypedNum (input)
-keyTypedDec (input)
