### ISSUE TITLE
Error fecha nacimiento para Ingreso o Modificación

### ISSUE THREAD

**Issue by andreagiaco** [fedeolivera1/ProyFinal2017Dsk#16]
Muestra   fecha invalida solo por mes y dia, año deja poner cualquier digito (si se ponen 2 digitos en vez de 4 deja la última fecha correcta que se haya usado aunque sea de otro cliente)

**Comment by fedeolivera1** [comment]
Se modifico el método de control de las fechas para la pf. De todos modos, este controla por las fechas que el sistema admite (DateFormat.SHORT).
