### ISSUE TITLE
Eliminación de Empresa Proveedor Error

### ISSUE THREAD

**Issue by andreagiaco** [fedeolivera1/ProyFinal2017Dsk#19]
No elimina Empresa proveedor ni muestra error. No hace nada, ni elimina.

**Comment by fedeolivera1** [comment]
El método se encontraba comentado desde el boton mismo. De todos modos, luego de modificar esto, hubo que modificar la restricción "on delete cascade" al igual que anteriormente se había hecho con "on update", para que permita la eliminación en cascada de pers_fisica con persona y pers_juridica con persona.
